name: Validate Release Version
description: 'Validates the input release version variable'

inputs:
  version:
    description: Release Version
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate Release Version
      shell: bash
      run: |
        if [[ ! ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. (e.g. 1.0.0)"
          exit 1
        fi
