name: Compile
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release (e.g. 1.0.0)
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        description: Version to release (e.g. 1.0.0)
        required: true

env:
  TZ: "Asia/Tokyo"

jobs:
  compile:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      RELEASE_VERSION: ${{ github.event.inputs.version }}
    permissions:
      contents: write
    strategy:
      matrix:
        arch:
          [
            "x86_64-unknown-linux-gnu",
            "x86_64-apple-darwin",
            "aarch64-apple-darwin",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.39.4"
      - uses: ./.github/actions/validate_version
        with:
          version: ${{ env.RELEASE_VERSION }}
      - name: Compile
        run: deno compile --output deepl --target ${{ matrix.arch }} --allow-read --allow-env --allow-net main.ts --lite
      - name: Compress
        run: tar -czf deepl-${{ matrix.arch }}.tar.gz deepl
      - name: Upload to Release
        run: gh release upload v${{ env.RELEASE_VERSION }} deepl-${{ matrix.arch }}.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
