name: Release
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  compile:
    runs-on: ubuntu-20.04
    needs: [ci]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.39.4"
      - name: Compile
        run: deno task compile
      - name: Test run
        run: ./deepl --help
      - name: Compress
        run: tar czvf deepl.tar.gz ./deepl
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: deepl-cli
          path: /home/runner/work/deepl-cli/deepl-cli
          compression-level: 0
