name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version to release (e.g. 1.0.0)
        required: true

env:
  TZ: "Asia/Tokyo"

jobs:
  validate:
    runs-on: ubuntu-20.04
    env:
      RELEASE_VERSION: ${{ github.event.inputs.version }}
      if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate_version
        with:
          version: ${{ env.RELEASE_VERSION }}

  ci:
    needs: [validate]
    if: github.ref_name == 'main'
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: [ci]
    env:
      RELEASE_VERSION: ${{ github.event.inputs.version }}
    permissions:
      contents: write
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate_version
        with:
          version: ${{ env.RELEASE_VERSION }}
      - name: Setup Release Tag Name
        run: echo "RELEASE_TAG=v$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Create Release Note
        run: gh release create $RELEASE_TAG --target ${{ github.ref_name }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile:
    needs: [release]
    if: github.ref_name == 'main'
    uses: ./.github/workflows/compile.yml
    permissions:
      contents: write
    with:
      version: ${{ github.event.inputs.version }}
