name: Release
on:
  release:
    types: [created]
jobs:
  manual_process:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.39.4"
      - name: Compile
        run: deno task compile
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: deepl
          path: deepl
